
/**
 * Demo/mock plants (formerly in DashboardPlantList.tsx)
 */
const demoPlants = [
  {
    image: "/placeholder.svg",
    name: "Fiddle Leaf Fig",
    price: "$15",
    distance: "2 km",
    location: "Sunnydale",
    seller: "Maria",
    sellerId: "seller-uid-1",
    type: "indoor",
  },
  {
    image: "/placeholder.svg",
    name: "Snake Plant",
    price: "$12",
    distance: "5 km",
    location: "Greenfield",
    seller: "James",
    sellerId: "seller-uid-2",
    type: "indoor",
  },
  {
    image: "/placeholder.svg",
    name: "Monstera Deliciosa",
    price: "$25",
    distance: "1.5 km",
    location: "Oakwood",
    seller: "Jessica",
    sellerId: "seller-uid-3",
    type: "indoor",
  },
  {
    image: "/placeholder.svg",
    name: "Aloe Vera",
    price: "$8",
    distance: "3 km",
    location: "Midtown",
    seller: "Olivia",
    sellerId: "seller-uid-4",
    type: "succulent",
  },
  {
    image: "/placeholder.svg",
    name: "Spider Plant",
    price: "$10",
    distance: "4.5 km",
    location: "Maplewood",
    seller: "Leo",
    sellerId: "seller-uid-5",
    type: "indoor",
  },
  {
    image: "/placeholder.svg",
    name: "Pothos",
    price: "$9",
    distance: "4 km",
    location: "Riverside",
    seller: "Sofia",
    sellerId: "seller-uid-6",
    type: "indoor",
  },
  {
    image: "/placeholder.svg",
    name: "Cactus Mini",
    price: "$6",
    distance: "6 km",
    location: "Hillcrest",
    seller: "Amber",
    sellerId: "seller-uid-7",
    type: "succulent",
  },
  {
    image: "/placeholder.svg",
    name: "Peace Lily",
    price: "$11",
    distance: "2.5 km",
    location: "Sunnydale",
    seller: "Maria",
    sellerId: "seller-uid-1",
    type: "flower",
  },
  {
    image: "/placeholder.svg",
    name: "ZZ Plant",
    price: "$18",
    distance: "7 km",
    location: "Evergreen",
    seller: "Noah",
    sellerId: "seller-uid-8",
    type: "indoor",
  },
  {
    image: "/placeholder.svg",
    name: "Rubber Plant",
    price: "$20",
    distance: "1 km",
    location: "Oakwood",
    seller: "Jessica",
    sellerId: "seller-uid-3",
    type: "indoor",
  },
  {
    image: "/placeholder.svg",
    name: "Outdoor Bonsai",
    price: "$22",
    distance: "8 km",
    location: "Garden Oaks",
    seller: "Daniel",
    sellerId: "seller-uid-9",
    type: "outdoor",
  },
  {
    image: "/placeholder.svg",
    name: "Daisy",
    price: "$5",
    distance: "12 km",
    location: "Meadow Lane",
    seller: "Emma",
    sellerId: "seller-uid-10",
    type: "flower",
  },
  {
    image: "/placeholder.svg",
    name: "Succulent Mix",
    price: "$14",
    distance: "10 km",
    location: "Brookfield",
    seller: "Leo",
    sellerId: "seller-uid-5",
    type: "succulent",
  },
];

export default demoPlants;
